### ISSUE TITLE
Unable to purge extension

### ISSUE THREAD

**Issue by rxu** [phpBBSEO/usu#51]
Trying to purge the extension (Manage extensions -> phpBB SEO Ultimate SEO URL -> Disable -> Delete data) ACP error is thrown:

Something went wrong during the request and an exception was thrown. The changes made before the error occurred were reversed to the best of our abilities, but you should check the board for errors.
A required module does not exist: ACP_MOD_REWRITE

**Comment by everflux** [comment]
I have the same problem, used fresh phpbb 3.1.3 files and usu from git, but old database which was migrated from phpbbseopremod 3.0 with phpbb 3.1.3 upgraer.
Neither is the extension shown after enabling, nor can I purge the data because of the missing ACP_MOD_REWRITE error.

Is there any way to clean the databse of the old settings and start from scratch?
